[package]
name = "rust-game"
version = "0.1.0"
authors = ["ryanisnan <ryanisnan@gmail.com>"]

[dependencies]
rand = "0.3.16"
ggez = "0.3.3"

[features]
# If this feature is enabled, it will add <cargo root dir>/resources/ to
# the resource search path.
cargo-resource-root = []
