[package]
name = "rust-game"
version = "0.1.0"
authors = ["ryanisnan <ryanisnan@gmail.com>"]

[dependencies]
rand = "0.3.16"
piston = "0.32.0"
piston_window = "0.61.0"
piston2d_sprite = "0.36.0"
find_folder = "0.3.0"
